name: Minify with node-minify
on:
  push:
    branches: [ production ]
        

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Minify with node-minify Action
        uses: eduardo92005-debug/purge-css-action@v1
