name: Minify with node-minify
on:
  push:
    branches: [ production ]
env:
  test_var: 'teste'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Minify with node-minify Action
        uses: eduardo92005-debug/purge-css-action@v5
        with:
          test_var: ${{ env.TEST_VAR }} 
